[mypy]
python_version = 3.9
strict = True
disallow_untyped_defs = True
ignore_missing_imports = False

# Third-party libraries without type stubs.
[mypy-cv2.*]
ignore_missing_imports = True

[mypy-environs.*]
ignore_missing_imports = True

[mypy-sqlmodel.*]
ignore_missing_imports = True

