[[plugins]]
id = "lightly-plugins-bbox-auto-propagation"
name = "BBox auto propagation"
description = "xyz"
source = "local:plugins/bbox_auto_propagation"
maintainer = "lightly"
tags = ["auto-labeling", "tracking"]
