[project]
name = "lightly-studio-plugins"
version = "0.1.0"
description = "All Lightly Studio plugins"
requires-python = ">=3.8"
dependencies = [
"lightly_plugins_bbox_auto_propagation_nano_tracker",
]

[tool.uv.sources]
lightly_plugins_bbox_auto_propagation_nano_tracker = { workspace = true }

[tool.uv.workspace]
members = ["plugins/*"]
